version: '3'
services:
  api:
    container_name: aggme-web
    restart: always
    build: .
    ports:
      - "4000:3000" # Redirige el tráfico del puerto 4000 al puerto 80
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf:/etc/nginx/conf.d
