version: '3'
services:
  api:
    container_name: aggme-web
    restart: always
    build: .
    ports:
      - "4000:80"  # Redirige el tráfico del puerto 4000 al puerto 80
  nginx:
    container_name: aggme-nginx
    restart: always
    image: nginx
    ports:
      - "80:80"  # Expone el puerto 80 para acceder a Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Monta el archivo de configuración de Nginx